name: Converter inscrição em JSON

on:
  issues:
    types: [opened]

jobs:
  salvar:
    if: contains(github.event.issue.labels.*.name, 'inscricao')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Criar pasta de dados
        run: mkdir -p data

      - name: Salvar resposta
        run: |
          NAME="data/resposta-$(date +'%Y-%m-%dT%H-%M-%S').json"
          cat <<EOF > $NAME
          {
            "nome": "$(echo "${{ github.event.issue.title }}" | sed 's/Nova inscrição: //')",
            "discord_id": "$(echo "${{ github.event.issue.body }}" | grep 'ID Discord' | cut -d':' -f2- | xargs)",
            "idade": "$(echo "${{ github.event.issue.body }}" | grep 'Idade' | cut -d':' -f2- | xargs)",
            "cargo": "$(echo "${{ github.event.issue.body }}" | grep 'Cargo' | cut -d':' -f2- | xargs)",
            "motivo": "$(echo "${{ github.event.issue.body }}" | grep 'Motivo' | cut -d':' -f2- | xargs)",
            "tempo": "$(echo "${{ github.event.issue.body }}" | grep 'Tempo' | cut -d':' -f2- | xargs)"
          }
          EOF
          cat $NAME

      - name: Commit e Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/
          git commit -m "Nova inscrição convertida"
          git push
